### ISSUE TITLE
main.js 有误

### ISSUE THREAD

**Issue by Kuangcp** [landray/Solo#2]
> vue init landray/solo-boilerplate my-project # my-project 为你的项目名称
这种方式 报错， main.js 最后一行右大括号前少了一个空格， 添加就运行成功 了

**Comment by oe** [comment]
抱歉, 这个模板暂时未维护, 直接从公司网站上 `下载应用模板` 来开始新应用吧

**Comment by oe** [comment]
下载地址 
http://kk5.landray.com.cn:6789/solo/2.1.14/index.html#get-started

**Comment by Kuangcp** [comment]
OK
